package DAO;





import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;





import java.util.ArrayList;

import business.prodotti.Assemblaggio;

/**
 * @author paolo maione
 */
public class AssemblaggioDAO {

    
    public AssemblaggioDAO() {
    }
    
    /*
	 * Crea una nuova oggetto persistente della classe Assemblaggio . 
	*/
    static public void create(Assemblaggio assObj) throws SQLException  {
		Connection c = DBManager.getConnectionDB();
		PreparedStatement s = c.prepareStatement("INSERT INTO ASSEMBLAGGIO (CODICECIRCUITO, CODICECOMPONENTE, QTA) VALUES (?,?,?)");
		
		s.setString(1, assObj.getCodiceCircuito());
		s.setString(2, assObj.getCodiceComponente());
		s.setInt(3, assObj.getNumeroUnita());
		
		try {
			s.executeUpdate();
			ResultSet rs = s.getGeneratedKeys();
			if (rs.next() == false) {
				throw new SQLException("ID value was not autogenerated!");
			}
			
		} finally {
			s.close();
			DBManager.closeConnection();
		}
		
    }
		
		
		/*
		 * Elimina l'oggetto persistente a.
		 */
		static public void delete(Assemblaggio ass) throws SQLException {
		        Connection c = DBManager.getConnectionDB();
				Statement stmt = c.createStatement();
				
				stmt.executeUpdate("DELETE FROM ASSEMBLAGGIO WHERE CODCIRCUITO="+ass.getCodiceCircuito());
				stmt.close();
				
				DBManager.closeConnection();
				
		}
	
		/*
		 * aggiorna il numero di unità impiegate per la coppia circuito-componente
		 */
		public static void update(Assemblaggio ass) throws SQLException {
			Connection conn = DBManager.getConnectionDB();
			PreparedStatement stmt = conn.prepareStatement("UPDATE ASSEMBLAGGIO SET QTA=? WHERE CODICECIRCUITO=? AND CODCOMPONENTE=?");
			stmt.setInt(1, ass.getNumeroUnita());
			stmt.setString(2, ass.getCodiceCircuito());
			stmt.setString(3, ass.getCodiceComponente());
			stmt.executeUpdate();
			
			stmt.close();
			DBManager.closeConnection();

		}	
		
		
		
		/*
		 *   legge gli assemblaggi associati al circuito con codice cod
		 *      e li restituisce in un array list
		 */
		public static ArrayList<Assemblaggio> leggi(String cod) throws SQLException{
			Connection conn= DBManager.getConnectionDB();
			PreparedStatement stmt = conn.prepareStatement("SELECT * FROM ASSEMBLAGGIO WHERE CODCIRCUITO=?");
			stmt.setString(1, cod);
			ResultSet res=stmt.executeQuery();
			
			ArrayList<Assemblaggio> listaAssemblaggi= new ArrayList<Assemblaggio>();
			while (res.next()) {
				  String  r1=res.getString("CODCIRCUITO");
				  String  r2=res.getString("CODCOMPONENTE");
				  Integer r3=res.getInt("QTA");
				  listaAssemblaggi.add(new Assemblaggio(r1, r2, r3));
				}
			res.close();
			stmt.close();
			DBManager.closeConnection();
			
			return listaAssemblaggi;
			
		}
		
}

